// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4gHRjbYH7aD723iEEF1zZyJAi7tQjYg',
    appId: '1:1037391974349:web:d16b569b54910d6ea17e84',
    messagingSenderId: '1037391974349',
    projectId: 'fullstack-instagram-clon-49944',
    authDomain: 'fullstack-instagram-clon-49944.firebaseapp.com',
    storageBucket: 'fullstack-instagram-clon-49944.firebasestorage.app',
    measurementId: 'G-2ZX9KV8RN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnEZZpBg-CzOPAuNpxkG9-OCH0ei7dRs',
    appId: '1:1037391974349:android:50e831ba38e67052a17e84',
    messagingSenderId: '1037391974349',
    projectId: 'fullstack-instagram-clon-49944',
    storageBucket: 'fullstack-instagram-clon-49944.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCXhmaW_DpRW51HIFOdl6Z5yPaqq2o3Y',
    appId: '1:1037391974349:ios:d10613d651afe61ca17e84',
    messagingSenderId: '1037391974349',
    projectId: 'fullstack-instagram-clon-49944',
    storageBucket: 'fullstack-instagram-clon-49944.firebasestorage.app',
    iosBundleId: 'com.example.fullstackInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBCXhmaW_DpRW51HIFOdl6Z5yPaqq2o3Y',
    appId: '1:1037391974349:ios:d10613d651afe61ca17e84',
    messagingSenderId: '1037391974349',
    projectId: 'fullstack-instagram-clon-49944',
    storageBucket: 'fullstack-instagram-clon-49944.firebasestorage.app',
    iosBundleId: 'com.example.fullstackInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF4gHRjbYH7aD723iEEF1zZyJAi7tQjYg',
    appId: '1:1037391974349:web:bd36a8840000dba4a17e84',
    messagingSenderId: '1037391974349',
    projectId: 'fullstack-instagram-clon-49944',
    authDomain: 'fullstack-instagram-clon-49944.firebaseapp.com',
    storageBucket: 'fullstack-instagram-clon-49944.firebasestorage.app',
    measurementId: 'G-WV6MM0Q0K0',
  );
}
